### ISSUE TITLE
update Figma-Mockup

### ISSUE THREAD

**Issue by werzingerma** [th-nuernberg/memtest#14]
Mockup-Update:
- Input-View --> Input-Daten des Users
- Calibration-View --> Drag&Drop, Klick und Audio Tutorial
- QR-Code Erkennung --> Verschieben zum Start der App
- Tutorial-Messages zum Anfang jedes Tests
- Tutorial-Video am Anfang entfernen
- Zweiten Weg (Selftest) entfernen --> kommt in Version 2.0
- Testüberschriften --> Sinnvolle Testüberschriften überlegen (wie der Test funktioniert wird davor gesagt(Tutorial-Messages))
- End-View --> Dankes-Nachricht bzw Info das der Test zu Ende ist

**Comment by werzingerma** [comment]
Mockup ist upgedatet unter folgenden Link:

https://www.figma.com/file/uvXdw1thgLTFZhM29WLz8p/Secure-Questionare---Mockup?type=design&node-id=976%3A3480&mode=design&t=k1r8Hf9wRQYzPrlO-1

**Comment by ChipCracker** [comment]
QR-Code View muss geändert werden. Es soll kein QR-Code auf dem iPad generiert werden, sonder es soll ein QR-Code eingelesen werden. (Data: RSA public key, studienId)

**Comment by werzingerma** [comment]
@ChipCracker Mockup ist angepasst.
- Datenübermittlung-View öffnet jetzt die Kamera um den QR-Code einzulesen
- Nach dem Scannen des QR-Codes durch die Kamera wird dann die DataInput-View geöffnet
