### ISSUE TITLE
update the Input View in the Figma-Mockup

### ISSUE THREAD

**Issue by ChipCracker** [th-nuernberg/memtest#20]
Die InputView, soll folgende Eingaben beinhalten:

Vorname ?
Name ?
Alter in Jahren (explizit nicht das Geburtsdatum)
Höchster Bildungsabschluss (3 Auswahlmöglichkeiten - Radiobuttons?)
- kein Abschluss
- Schulabschluss , Ausbildungsberuf
- Techniker, Meister oder Hochschulabschluss

**Comment by werzingerma** [comment]
Mockup ist angepasst
